apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: test1
  labels:
    strimzi.io/cluster: simple-kafka-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
