image:
  repository: quay.io/causely/chaosmania
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 64Mi

serviceMonitor:
  # When set true then use a serviceMonitor to configure scraping
  enabled: false

otlp:
  enabled: true
  endpoint: "http://opentelemetry-collector.default:4318" # http://tempo.monitoring:4318
  insecure: true

datadog:
  enabled: false
