image:
  repository: quay.io/causely/chaosmania
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 6000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 512Mi

serviceMonitor:
  # When set true then use a serviceMonitor to configure scraping
  enabled: false

otlp:
  enabled: false
  endpoint: "" # http://tempo.monitoring:4318
  insecure: true

datadog:
  enabled: false